name: Documentation Update

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull changes into documentation branch
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "Automated"
          git checkout documentation
          git pull origin main
          git add .
          git commit -m "Update documentation"
          git push origin documentation
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
