name: Daily Documentation Scrape

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run documentation scrape
        run: |
          python src/documentation_scrape.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add outputs/*.md
          git commit -m "Update documentation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
